spring.application.name=crowdfunding

spring.datasource.url=jdbc:postgresql://localhost:5432/crowdfunding
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=INFO

# Web3j Configuration
web3j.client-address=http://localhost:8545
web3j.gas-price=20000000000
web3j.gas-limit=6721975

# Contract Addresses
contract.admin-manager.address=0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
contract.proposal-manager.address=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
contract.milestone-manager.address=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
contract.fund-manager.address=0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9

# JWT Configuration
# Custom secret key must be at least 256 bits long
jwt.secret=SMUKzonEgI0nCWFVBfyQKfaljaQqBe7qntGY0YoyhrNg36lZEe7F2XQhZe0fwUKx
# Expiration time: 30 minutes
jwt.expiration=1800000